### ISSUE TITLE
Implement some cool animation instead of Loading text

### ISSUE THREAD

**Issue by cwidevs** [cwipedia-in/home.cwipedia.in#19]
Implement some cool animation instead of Loading text , animation like loading curly braces
![Screenshot from 2021-10-09 13-27-35](https://user-images.githubusercontent.com/79762195/136649746-38776b71-4ca8-48ca-aabd-26584b333451.png)
 
![CPT2110091332-948x574](https://user-images.githubusercontent.com/50539402/136649849-02f67d05-ce41-4cd0-babc-21a66e9b19ce.gif)

**Comment by Pervolarakis** [comment]
![lazy](https://user-images.githubusercontent.com/56447146/136650820-e35f1672-acb7-440e-99de-a1588219cf84.png)
