### ISSUE TITLE
Padding Requirement in Services Cards

### ISSUE THREAD

**Issue by kumar-tushar** [cwipedia-in/home.cwipedia.in#28]
**Is your feature request related to a problem? Please describe.**
The text and images get in touch with each other on scrolling cursor on cards which doesn't looks nice.

**Describe the solution you'd like**
I want to give some margin over the text.

**BEFORE**
![Screenshot (229)_LI](https://user-images.githubusercontent.com/56949668/136682828-baab952f-d720-45a5-8ff7-38514b24a1ef.jpg)

#
#
**AFTER**

![Screenshot (230)_LI](https://user-images.githubusercontent.com/56949668/136682870-2eee1a75-329e-4b1d-93c4-d8cc6c228a2d.jpg)

**Comment by cwidevs** [comment]
> **Is your feature request related to a problem? Please describe.** The text and images get in touch with each other on scrolling cursor on cards which doesn't looks nice.
> 
> **Describe the solution you'd like** I want to give some margin over the text.
> 
> **BEFORE** ![Screenshot (229)_LI](https://user-images.githubusercontent.com/56949668/136682828-baab952f-d720-45a5-8ff7-38514b24a1ef.jpg)
> 
> **AFTER**
> 
> ![Screenshot (230)_LI](https://user-images.githubusercontent.com/56949668/136682870-2eee1a75-329e-4b1d-93c4-d8cc6c228a2d.jpg)

okay, sounds technical but this issue will not label as hackoberfest, If you still wanna work on this then please go ahead
