### ISSUE TITLE
Add Accordion 

### ISSUE THREAD

**Issue by 0shivamh** [cwipedia-in/home.cwipedia.in#33]
![Screenshot from 2021-10-11 00-01-31](https://user-images.githubusercontent.com/50539402/136709050-4e34f321-d04d-4d32-a312-d81f65e30146.png)
Accordion QAN:

1. How Can I Contact You?
If you are facing out a problem related to Website Control or Study Material, please go through the Contact Us section Otherwise we are reachable at business@cwipedia.in

2. Do you sponsor Final Year Projects?
Yes, we do that. For this your need to contact us at business@cwipedia.in Our Team will get back to you.

3. How to download MSBTE Study Resources?
Hold on, we are here to answer your question, You Can able to download all study material under Diploma Engineering Section or Using Our Android App " MSBTE Practice" and "MSBTE Syllabus".

**Comment by TaniyaFaisal** [comment]
Hey! I would like to work on this.

**Comment by 0shivamh** [comment]
> Hey! I would like to work on this.

okay, I'm assigning this to you
